# @name api/auth/register
POST {{DataFlowHub_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Brian Antonio",
  "lastName": "Gaitán Corea",
  "email": "bgaitan2@test.com",
  "userName": "bagc",
  "password": "mortadela01"
}

###

# @name api/auth/login
POST {{DataFlowHub_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "userName": "bagc",
  "password": "mortadela01"
}

> {%
    client.global.set("auth_token", response.body.data.token);
    client.global.set("refresh_token", response.body.data.refreshToken);
%}

###

# @name api/auth/refresh-token
POST {{DataFlowHub_HostAddress}}/api/auth/refresh-token
Content-Type: application/json

{
  "token": "{{auth_token}}",
  "refreshToken": "{{refresh_token}}"
}

> {%
    client.global.set("auth_token", response.body.data.token);
    client.global.set("refresh_token", response.body.data.refreshToken);
%}

###

# @name api/student/create
POST {{DataFlowHub_HostAddress}}/api/student
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstName": "Juan",
  "lastName": "Perez",
  "email": "juan.perez@test.com",
  "password": "Password123!",
  "studentCode": "ST001",
  "dateOfBirth": "2000-01-01T00:00:00Z",
  "address": "Calle Falsa 123"
}

###

# @name api/student/get-paged
GET {{DataFlowHub_HostAddress}}/api/student?pageNumber=1&pageSize=10
Authorization: Bearer {{auth_token}}

###

# @name api/teacher/create
POST {{DataFlowHub_HostAddress}}/api/teacher
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "firstName": "Maria",
  "lastName": "Lopez",
  "email": "maria.lopez@test.com",
  "password": "Password123!",
  "employeeNumber": "EMP001",
  "specialization": "Matematicas",
  "title": "Licenciada"
}

###

# @name api/teacher/get-paged
GET {{DataFlowHub_HostAddress}}/api/teacher?pageNumber=1&pageSize=10
Authorization: Bearer {{auth_token}}